# Generated by Django 4.1.5 on 2023-01-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveSmallIntegerField()),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.cliente')),
            ],
        ),
    ]
