# Generated by Django 4.1.5 on 2023-01-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_rename_fecha_pago_pago_fecha_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='codigo_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.actividad'),
        ),
    ]
