# Generated by Django 4.1.5 on 2023-01-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_actividad_pago_codigo_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.actividad')),
                ('dni_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.cliente')),
            ],
        ),
    ]
