# Generated by Django 4.1.5 on 2023-01-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_inscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='codigo_actividad',
            new_name='actividad',
        ),
    ]
